### ISSUE TITLE
auto ssl config option for nginx

### ISSUE THREAD

**Issue by wetlyrics** [licess/lnmp#4]
is it possible to add  a menu like:

do you add ssl config under nginx?
it will config everything for SSL under NGINX
just get the .crt from the provider and replace through FTP the self-signed SSL and DONE

you have to take care of SSL because GOOGLE priority SSL website and the myth is SSL config is only possible for Rocket Engineer:} cause it's hard to config

people will buy more VPS from you only because if your lnmp software has that auto SSL feature

then people don't need to become Rocket scientist!!

**Comment by licess** [comment]
This feature has been added in v1.4 and thank you for your support.
